version: "3.9"

services:
  redis:
    image: redis:alpine
  web:
    image: velinovasen/bethub
    build: .
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost
      - DEBUG=False
      - DB_NAME=bethub_rebuild
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    command: gunicorn bethub.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery_worker:
    build: .
    command: celery -A bethub worker -l info --uid=nobody -P solo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 50M
#        reservations:
#          cpus: '0.25'
#          memory: 20M
    restart: on-failure
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis
  celery_beat:
    build: .
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    command: celery -A bethub beat -l info
    depends_on:
      - web
      - db
      - redis
      - celery_worker
    restart: on-failure
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bethub_rebuild
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bianconeroo931
    volumes:
      - .:/code
