version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bethub_rebuild
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bianconeroo931
  web:
    image: velinovasen/bethub
    build: .
    environment:
      - ALLOWED_HOSTS=localhost
      - DEBUG=False
      - DB_NAME=bethub_rebuild
      - DB_USER=postgres
      - DB_PASSWORD=bianconeroo931
      - DB_HOST=db
      - DB_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db